import { Index } from "ts-functional/dist/types";

export const figureMap:Index<string> = {
    "119":"Wapi Pu",
    "118":"Vincent Parker",
    "117":"Vicky 4 Male",
    "116":"Vicky 3",
    "115":"Vicky 2",
    "114":"Vicky 1",
    "113":"Ugly Boy",
    "112":"Ug!",
    "111":"Toon Baby",
    "110":"The Girl 4",
    "109":"The Girl",
    "108":"The Freak",
    "107":"Terai Yuki 2",
    "106":"Sydney",
    "105":"Stephanie 3 Petite",
    "104":"Staci",
    "125":"Skye",
    "103":"Sara",
    "102":"Sam",
    "101":"Sadie",
    "100":"Rosy Cheeks Lina",
    "99":"Ralphling",
    "98":"Pygmy",
    "97":"Pretty3D Base (V4)",
    "96":"Pretty3D Base (V3)",
    "95":"Preteen Girl",
    "94":"Preteen Boy",
    "93":"Preschool Girl",
    "92":"Preschool Boy",
    "91":"PaperDoll Male",
    "90":"PaperDoll Female",
    "89":"P6 Kate",
    "88":"P6 Jessi",
    "87":"P6 James",
    "86":"P6 Ben",
    "85":"P5 Will",
    "84":"P5 Penny",
    "83":"P5 Judy",
    "82":"P5 Don",
    "81":"P4 Male",
    "80":"P4 Infant",
    "79":"P4 Girl",
    "78":"P4 Female",
    "77":"P4 Boy",
    "76":"Obama",
    "75":"Near Me",
    "74":"Nana",
    "73":"Minotaur",
    "72":"Millennium Baby 3",
    "71":"Miki 2",
    "70":"Miki 1",
    "69":"Mike 3",
    "68":"Mike 2",
    "67":"Mike 1",
    "66":"Maybe",
    "20":"Maya Doll",
    "65":"Matt 3",
    "64":"Mannequin",
    "63":"Maddie 3",
    "62":"Luke 3",
    "61":"Loik",
    "60":"Lil' Bub",
    "129":"Laura 3",
    "59":"LaRoo 2",
    "58":"Kyle 1.5",
    "57":"Kururu",
    "56":"Krystal SF",
    "55":"Krystal",
    "54":"Koshini 2",
    "53":"Koshini",
    "52":"Kit",
    "51":"Kiki",
    "50":"Jinkie",
    "49":"Jager",
    "48":"Ichiro 2",
    "47":"Ichiro",
    "46":"Hiro 4",
    "45":"Hiro 3",
    "44":"HER",
    "43":"Gumdrops",
    "42":"Gramps",
    "41":"Gloria",
    "40":"G2 Koji",
    "39":"G2 Kelvin",
    "37":"G2 Jessi",
    "38":"G2 James",
    "35":"Furrette",
    "36":"Furraldo",
    "34":"FemaSu",
    "33":"F202 Dollie",
    "32":"Evelinne",
    "127":"Eva",
    "31":"E.B.E.",
    "30":"Dennis",
    "29":"Decoco",
    "28":"David 3",
    "27":"CS Raptoid",
    "26":"Clark",
    "25":"Chip",
    "24":"Chibibel",
    "124":"Britta",
    "126":"Bong",
    "23":"Ball Joint Doll",
    "22":"Bacon",
    "21":"Apollo Maximus",
    "19":"Anime Doll",
    "18":"Amanda",
    "17":"Alice 2.0",
    "16":"Alice 1.5",
    "15":"Alexa 2",
    "128":"Aiko 4",
    "14":"Aiko 3",
    "13":"AF Diana",
    "147":"La Femme",
    "150":"Genesis 9",
    "146":"Genesis 8",
    "145":"Genesis 3",
    "142":"Dusk",
    "141":"SuzyQ 2",
    "137":"Michelle",
    "12":"Mike 4",
    "143":"Star",
    "11":"Cookie",
    "10":"Vicky 4",
    "138":"Dawn",

    "Stephanie 4": "Stephanie 4",
    "Yweeb": "Yweeb",
    "The Brute": "The Brute",
    "Anubis": "Anubis",
    "Sidd the Kid": "Sidd the Kid",
    "Gosha": "Gosha",
    "Doctor Pitterbill": "Doctor Pitterbill",
    "Hein": "Hein",
    "Pickles": "Pickles",
}

export const figureSynonyms:Index<string> = {
    "V4":"Vicky 4",
    "V3":"Vicky 3",
    "V2":"Vicky 2",
    "V1":"Vicky 1",
    "V4M":"Vicky 4 Male",
    "M4":"Mike 4",
    "M3":"Mike 3",
    "M2":"Mike 2",
    "M1":"Mike 1",
    "A3": "Aiko 3",
    "A4": "Aiko 4",
    "H3": "Hiro 3",
    "H4": "Hiro 4",
    "Koshini2": "Koshini 2",
    "Koshini1": "Koshini",
    "Laura3": "Laura 3",
    "Near_Me": "Near Me",
    "TY2": "Terai Yuki 2",
    "BJD": "Ball Joint Doll",
    "laura3": "Laura 3",
    "NearMe": "Near Me",
    "UG!": "Ug!",
    "Drakelot Minotaur": "Minotaur",
    "V4.2": "Vicky 4",
    "Maddie": "Maddie 3",
    "Matt": "Matt 3",
    "Terai Yuki2": "Terai Yuki 2",
    "Vicky 4.2 Complete": "Vicky 4",
    "Alexa2": "Alexa 2",
    "Michael 4": "Mike 4",
    "AFDiana": "AF Diana",
    "Stephanie Petite 3": "Stephanie 3 Petite",
    "SuzyQ": "SuzyQ 2",
    "Michael 2": "Mike 2",
    "Michael 1": "Mike 1",
    "Michael 3": "Mike 3",
    "Victoria 2": "Vicky 2",
    "Victoria 3": "Vicky 3",
    "Victoria 4": "Vicky 4",
    "Victoria 1": "Vicky 1",
    "Props": "Prop",
    "Textures": "Materials",
    "Xmas": "Christmas",
    "Anime/Maya Doll": "Anime Doll",
    "Characters": "Character",
    "Laura": "Laura 3",
    "Original Figures": "Original Figure",
    "Genesis 3 Female": "Genesis 3",
    "Genesis 8 Female": "Genesis 8",
    "Merchant Resources": "Merchant Resource",
};

export const translateRequires = (r:string):string[] => 
    r.includes("CrossDresser 2") ? ["Programs:CrossDresser 2"] :
    r.includes("CrossDresser 2") ? ["Programs:CrossDresser 2"] :
    r.includes("CrossDresser2") ? ["Programs:CrossDresser 2"] :
    r.includes("Crosserdresser 2") ? ["Programs:CrossDresser 2"] :
    r.includes("CrossDresser 3") ? ["Programs:CrossDresser 3"] :
    r.includes("Crossdresser 3") ? ["Programs:CrossDresser 3"] :
    r.includes("CrossDresser 4") ? ["Programs:CrossDresser 3"] :
    r.includes("Crossdresser 4") ? ["Programs:CrossDresser 4"] :
    r.includes("Poser") ? ["Programs:Poser"] :
    Object.values(figureMap).includes(r) ? [`Figures:${r}`] :
    Object.values(figureMap).includes(figureSynonyms[r]) ? [`Figures:${figureSynonyms[r]}`] :

    r === "Anime or Maya Doll" ? ["Figures:Anime Doll", "Figures:Maya Doll"] :
    r === "MayaX Ball Joint Doll" ? ["Figures:Maya Doll", "Figures:Ball Joint Doll"] :
    r === "ADMD" ? ["Figures:Anime Doll", "Figures:Maya Doll"] :
    r === "M2 or M1" ? ["Figures:Mike 2", "Figures:Mike 1"] :
    r === "Anime/Maya Doll" ? ["Figures:Anime Doll", "Figures:Maya Doll"] :
    r === "V2 or V1" ? ["Figures:Vicky 2", "Figures:Vicky 1"] :

    ["__Requires:" + r];
